### ISSUE TITLE
Updating README_AR.md

### ISSUE THREAD

**Issue by abdulelahsm** [ARBML/ARBML#23]
I thought I should kick off my contribution to this project by updating docs. I noticed that README_AR.md needs some update and since this project is all about Arabic NLP and its primary audience are Arabic speaking people, I think updating this document is essential when presenting this to newcomers. I'm available to work on this task if the team hasn't worked on it yet.

**Comment by zaidalyafeai** [comment]
@abdulelahsm yes please go ahead with it.
