### ISSUE TITLE
mobileBERT Demo Website

### ISSUE THREAD

**Issue by X7md** [ARBML/ARBML#26]
it's seem like maybe WebSite has an issue

https://arbml.github.io/ARBML/Interfaces/Website/ArabicSentimentClassificationBert/index.html

![Screenshot_20210503-222015_Chrome](https://user-images.githubusercontent.com/54203033/116922621-4b96a800-ac5e-11eb-803c-f9d56e14d3c9.png)
![Screenshot_20210503-222009_Chrome](https://user-images.githubusercontent.com/54203033/116922625-4d606b80-ac5e-11eb-9f33-35bb3aff95e1.png)
----

i use Chrome 
```
Google Chrome	90.0.4430.91 (Official Build) (32-bit)
Revision	6251784999d3102593e9f2ffe09d1d71bb231bd2-refs/branch-heads/4430@{#1341}
OS	Android 11; SM-A505F Build/RP1A.200720.012
```

**Comment by zaidalyafeai** [comment]
It seems you have to wait a bit before running the inference i.e when you see warming up finished in the console 
![image](https://user-images.githubusercontent.com/15667714/116923361-34a48580-ac5f-11eb-97ab-1df55c541b36.png)

**Comment by X7md** [comment]
> It seems you have to wait a bit before running the inference i.e when you see warming up finished in the console
> ![image](https://user-images.githubusercontent.com/15667714/116923361-34a48580-ac5f-11eb-97ab-1df55c541b36.png)

Yeah, I think that so,
Now it's working fine.... thanks.
